# alacritty.toml

[window]
dimensions = { columns = 104, lines = 32 }
padding = { x = 2, y = 2 }
title = "Alacritty"
resize_increments = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 10.0

[mouse]
hide_when_typing = true

# Base16 Theme

[colors]
draw_bold_text_with_bright_colors = true
cursor = { text = "#181818", cursor = "#d8d8d8" }

[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

# Apprentice Theme

# [colors]
# draw_bold_text_with_bright_colors = true
# cursor = { text = "#262626", cursor = "#BCBCBC" }

# [colors.primary]
# foreground = "#BCBCBC"
# background = "#262626"

# [colors.normal]
# black = "#1c1c1c"
# red = "#af5f5f"
# green = "#5f875f"
# yellow = "#87875f"
# blue = "#5f87af"
# magenta = "#5f5f87"
# cyan = "#5f8787"
# white = "#6c6c6c"

# [colors.bright]
# black = "#444444"
# red = "#ff8700"
# green = "#87af87"
# yellow = "#FFFFAF"
# blue = "#87AFD7"
# magenta = "#8787AF"
# cyan = "#5FAFAF"
# white = "#FFFFFF"

