require('config.nvim-base16')
require('config.nvim-web-devicons')
require('config.lualine')
require('config.luatab')
require('config.nvim-comment')
require('config.nvim-colorizer')
require('config.lf-vim')
require('config.vim-floaterm')
require('config.smart-splits')
require('config.zen-mode')
require('config.telescope')

