require('config.comment')
require('config.lualine')
require('config.luatab')
require('config.nvim-base16')
require('config.nvim-colorizer')
require('config.nvim-web-devicons')
require('config.smart-splits')
require('config.telescope')
require('config.zen-mode')

require('config.lf-vim')
require('config.vim-floaterm')
require('config.vimwiki')
